language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - pypy
install: 
  - pip install . --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --use-mirrors msgpack-pure; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install --use-mirrors msgpack-python; fi
script:
  - cd tests
  - python test_sofart.py
