language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - pypy
install: 
  - pip install . --use-mirrors
  - pip install msgpack-python
  - pip install unittest2
  - pip install isit
script: "cd tests && python test_sofart.py"
