language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy
install: 
  - pip install . --use-mirrors
  - pip install msgpack-python
  - pip install isit
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
script: "cd tests && python test_sofart.py"
